# Generated by Django 6.0.6 on 2026-06-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='icone',
            field=models.CharField(default='💊', max_length=10),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='code',
            field=models.CharField(default='FRN-000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='delai_livraison_jours',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='score_qualite',
            field=models.IntegerField(default=3),
        ),
    ]
