# Generated by Django 6.0.6 on 2026-06-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_categorie_icone_fournisseur_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='genre',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='client',
            name='pharmacie_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(default='PAT-000', max_length=50, unique=True),
        ),
    ]
