# Generated by Django 6.0.6 on 2026-06-14 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_client_cin_client_date_naissance_client_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.lotstock'),
        ),
        migrations.AddField(
            model_name='lotstock',
            name='bloque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lotstock',
            name='date_fabrication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotstock',
            name='pharmacie_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lotstock',
            name='quantite_initiale',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vente',
            name='code',
            field=models.CharField(default='VTE-000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='pharmacie_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vente',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(default='especes', max_length=20),
        ),
        migrations.AlterField(
            model_name='vente',
            name='numero',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
