# Generated by Django 6.0.6 on 2026-06-15 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_lignevente_lot_lotstock_bloque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='DIST-000', max_length=50, unique=True)),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_expedition', models.DateTimeField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('demande', 'Demandée'), ('valide', 'Validée'), ('expedie', 'Expédiée'), ('recu', 'Reçue'), ('annule', 'Annulée')], default='demande', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='PHA-000', max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('pharmacie', 'Pharmacie'), ('depot', 'Dépôt Central'), ('clinique', 'Clinique'), ('hopital', 'Hôpital')], default='pharmacie', max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('ice', models.CharField(blank=True, max_length=50)),
                ('rc', models.CharField(blank=True, max_length=50, verbose_name='Registre Commerce')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='pharmacie_id',
        ),
        migrations.RemoveField(
            model_name='lotstock',
            name='pharmacie_id',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='pharmacie_id',
        ),
        migrations.CreateModel(
            name='LigneDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.IntegerField(default=1)),
                ('quantite_envoyee', models.IntegerField(default=0)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacy.distribution')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.lotstock')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicament')),
            ],
        ),
        migrations.AddField(
            model_name='distribution',
            name='pharmacie_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions_recues', to='pharmacy.pharmacie'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='pharmacie_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions_envoyees', to='pharmacy.pharmacie'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='pharmacy.pharmacie'),
        ),
        migrations.AddField(
            model_name='client',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='pharmacy.pharmacie'),
        ),
        migrations.AddField(
            model_name='lotstock',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pharmacy.pharmacie'),
        ),
        migrations.AddField(
            model_name='vente',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='pharmacy.pharmacie'),
        ),
    ]
