# Generated by Django 6.0.6 on 2026-06-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_distribution_pharmacie_remove_client_pharmacie_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacie',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='boncommande',
            name='code',
            field=models.CharField(default='ACH-000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='date_livraison',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='date_fabrication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='numero_lot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='numero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('commande', 'Commandee'), ('recue', 'Recue'), ('annulee', 'Annulee')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='icone',
            field=models.CharField(default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='statut',
            field=models.CharField(choices=[('demande', 'Demandee'), ('valide', 'Validee'), ('expedie', 'Expediee'), ('recu', 'Recue'), ('annule', 'Annulee')], default='demande', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='rc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='type',
            field=models.CharField(choices=[('pharmacie', 'Pharmacie'), ('depot', 'Depot Central'), ('clinique', 'Clinique'), ('hopital', 'Hopital')], default='pharmacie', max_length=20),
        ),
    ]
