# Generated by Django 6.0.6 on 2026-06-15 21:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_pharmacie_options_boncommande_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='INV-000', max_length=50, unique=True)),
                ('user_id', models.IntegerField(default=1)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_finalisation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('finalise', 'Finalise'), ('annule', 'Annule')], default='en_cours', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='pharmacy.pharmacie')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_systeme', models.IntegerField(default=0)),
                ('stock_reel', models.IntegerField(default=0)),
                ('ecart', models.IntegerField(default=0)),
                ('ajustement_applique', models.BooleanField(default=False)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacy.inventaire')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaire_lignes', to='pharmacy.lotstock')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicament')),
            ],
        ),
    ]
