# Generated by Django 6.0.6 on 2026-06-16 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_inventaire_ligneinventaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('rupture', 'Rupture de stock'), ('stock_faible', 'Stock faible'), ('expiration_proche', 'Expiration proche'), ('expire', 'Produit expire'), ('point_commande', 'Point de commande atteint')], max_length=30)),
                ('niveau', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('danger', 'Critique')], default='warning', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.lotstock')),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicament')),
                ('pharmacie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacie')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
