# Generated by Django 6.0.6 on 2026-06-17 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_alerte'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetourClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='RET-000', max_length=50, unique=True)),
                ('date_retour', models.DateTimeField(default=django.utils.timezone.now)),
                ('motif', models.CharField(choices=[('defectueux', 'Produit defectueux'), ('expire', 'Produit expire'), ('erreur', 'Erreur de commande'), ('allergie', 'Allergie'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.client')),
                ('pharmacie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pharmacy.pharmacie')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='pharmacy.vente')),
            ],
            options={
                'ordering': ['-date_retour'],
            },
        ),
        migrations.CreateModel(
            name='LigneRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retournee', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.lotstock')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicament')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacy.retourclient')),
            ],
        ),
    ]
