# Generated by Django 6.0.6 on 2026-06-17 18:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_retourclient_ligneretour'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('user_nom', models.CharField(default='System', max_length=200)),
                ('action', models.CharField(max_length=200)),
                ('module', models.CharField(choices=[('Auth', 'Auth'), ('Medicaments', 'Medicaments'), ('Categories', 'Categories'), ('Fournisseurs', 'Fournisseurs'), ('Patients', 'Patients'), ('Pharmacies', 'Pharmacies'), ('Stock', 'Stock'), ('Ventes', 'Ventes'), ('Achats', 'Achats'), ('Distributions', 'Distributions'), ('Inventaires', 'Inventaires'), ('Retours', 'Retours'), ('Alertes', 'Alertes'), ('Systeme', 'Systeme')], default='Systeme', max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('pharmacie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacie')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
