# Generated by Django 6.0.6 on 2026-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_logactivite'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='seuil_depot',
            field=models.IntegerField(default=500, help_text='Seuil pour depot central'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='seuil_alerte',
            field=models.IntegerField(default=10, help_text='Seuil pour pharmacies'),
        ),
    ]
