# Generated by Django 6.0.6 on 2026-06-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_medicament_seuil_depot_alter_medicament_seuil_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='delai_securite_depot',
            field=models.IntegerField(default=30, help_text='Jours stock securite depot'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='delai_securite_pharmacie',
            field=models.IntegerField(default=7, help_text='Jours stock securite pharmacie'),
        ),
    ]
